# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true
    trusted_proxies: '127.0.0.1'

    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    enabled_locales: [ 'fr', 'en', 'de', 'sv', 'es' ]

    exceptions:
        # To prevent spammy logging in the tests where this is expected
        Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException:
            log_level: debug
        Symfony\Component\HttpKernel\Exception\HttpException:
            log_level: debug

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
