framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
            # Uncomment this line to use the Intl ICU formatter
            intl: ~ 