services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: symfony_prep_php
    user: www-data
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
