services:
  App\Service\DependencyInjectionTopic\Manager:
    public: true
    arguments:
      - '@logger'
    calls:
      - setRouter:
          - '@router'
    properties:
      twig: '@twig'

  App\Service\DependencyInjectionTopic\Handler:
    autowire: true
    public: true
    lazy: true

  App\Service\DependencyInjectionTopic\Parser:
    public: false

  App\Service\DependencyInjectionTopic\Processor:
    synthetic: true

  App\Service\DependencyInjectionTopic\Generator:
    shared: false

  some_abstract_service:
    abstract: true
    public: true
    calls:
        - setLogger: ['@logger']

  simple_service:
    class: App\Service\DependencyInjectionTopic\Connector
    parent: some_abstract_service

  App\Service\DependencyInjectionTopic\Mapper:
    properties:
      # Decode file name from 'BASE64_ENCODED_CONTENT_PATH', read that file, parse JSON and extract the KeyName
      value: '%env(key:KeyName:json:file:base64:BASE64_ENCODED_CONTENT_PATH)%'

  App\Service\DependencyInjectionTopic\Factory: ~

  app.profiler.built_by_static_factory:
    class: App\Service\DependencyInjectionTopic\Profiler
    factory: ['App\Service\DependencyInjectionTopic\StaticFactory', 'createService']
    public: true

  app.profiler.built_by_service_factory:
    class: App\Service\DependencyInjectionTopic\Profiler
    public: true
    factory: ['@App\Service\DependencyInjectionTopic\Factory', 'createService']

  App\Service\DependencyInjectionTopic\Aggregator: ~

  App\Service\DependencyInjectionTopic\ServiceWithMultipleDependencies:
    autowire: true
    autoconfigure: true

  App\Service\DependencyInjectionTopic\AnotherServiceWithMultipleDependencies:
    autowire: true
    autoconfigure: true

  App\Service\DependencyInjectionTopic\Monitor:
    arguments:
      - '@logger'

  App\Service\DependencyInjectionTopic\TrackerInterface: '@App\Service\DependencyInjectionTopic\Tracker'

  App\Service\DependencyInjectionTopic\Tracker: ~

  App\Service\DependencyInjectionTopic\OuterTrackerDecorator:
    decorates: App\Service\DependencyInjectionTopic\Tracker
    decoration_priority: 100
    arguments:
      - '@.inner'

  App\Service\DependencyInjectionTopic\TrackerDecorator:
    decorates: App\Service\DependencyInjectionTopic\Tracker
    decoration_priority: 200
    arguments:
      - '@.inner'

  app.first_collection:
    class: App\Service\DependencyInjectionTopic\Collection
    public: true
    arguments:
      - !tagged_iterator producer

  app.second_collection:
    class: App\Service\DependencyInjectionTopic\Collection
    public: true

  app.producer1:
    class: App\Service\DependencyInjectionTopic\Producer
    arguments:
      - 'producer1'
    tags:
      - producer

  app.producer2:
    class: App\Service\DependencyInjectionTopic\Producer
    arguments:
      - 'producer2'
    tags:
      - producer

  app.third_collection:
    class: App\Service\DependencyInjectionTopic\Collection
    public: true
    arguments:
      - !tagged_iterator special_tag1

  app.fourth_collection:
    class: App\Service\DependencyInjectionTopic\Collection
    public: true
    arguments:
      - !tagged_iterator special_tag2

  App\Service\DependencyInjectionTopic\SubProducer:
    autoconfigure: true

  App\Service\DependencyInjectionTopic\Provider:
    autoconfigure: true
