controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

custom_routes:
    resource: ../config/custom_routes.yaml
    prefix: /custom-prefix


redirect_route:
    path: /topic4/redirect
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    methods: [GET]
    defaults:
        route: route1
        permanent: false
        keepRequestMethod: true


custom_loader:
    resource: .
    type: custom_loader